### ISSUE TITLE
Migrate content over from old site

### ISSUE THREAD

**Issue by edisch** [edisch/viveelsueno#17]
https://modest-liskov-6d2578.netlify.com/

### /about

 Vive El Sueño, based in Nosara, Costa Rica, is an educational and financial empowerment program that aims to give Costa Rican nationals (Ticos) the skills, mentorship, and tools to open and sustain their own small businesses as a path to improved standards of living and financial independence.

While the boom in tourism and land development appears to have brought significant improvements in the quality of life in Nosara, recently released research shows that 25% of families still live in poverty. As recently as 2011 as many as 48% of households in Nosara and Samara still lacked at least one basic need. Our belief is that small businesses provide a much needed path to financial empowerment.

The goals of Vive El Sueño are to:
Provide educational workshops on topics such as Entrepreneurship, Finance, Marketing, Management, English Classes, and Life Coaching that will both support the opening of new small businesses and increase eligibility for senior level positions in existing businesses. Provide ongoing mentorship to Program Participants to foster continued growth in their businesses. Connect emerging business owners to crucial resources such as grants, loans, and professional services.

**Comment by Viveelsueno** [comment]
The Nosara Spanish Institute
![nosara-spanish-institiue-vive-el-sueno](https://user-images.githubusercontent.com/35813084/38326043-3a48f592-37f1-11e8-8b41-a24d57a32039.jpg)

**Comment by Viveelsueno** [comment]
Go Juice
<img width="419" alt="go juice logo" src="https://user-images.githubusercontent.com/35813084/38520016-f8bc814c-3bed-11e8-950e-585ac6626758.png">

**Comment by edisch** [comment]
@Viveelsueno Hey thanks for adding those.

I'm also going to need the content for the "Our Program" section. Just some general copy text of the foundation of the program highlights like the english classes etc, under 4 sections like how it appears currently in the design / website. Thanks.

**Comment by Viveelsueno** [comment]
Do you just want me to add a section for this year's trainings and some of
the photos?

**Comment by Viveelsueno** [comment]
To be clear, we would like to keep the previous years of program info if
that can work. If that works then I will add info for this years program
and new photos.  Sound good?

**Comment by Viveelsueno** [comment]
2017-2018 Program Information
The Vive El Sueño program and contained 5 main components:

1.  2 week/ 40 hour Intensive Business Trainings led by teaching group Yo Emprendedor held at the David Kitson Library. 
Topics included:
-Opportunities and Entrepreneurship
-Presentation Abilities
-Business Model and Map
-Costs, Finances & Negotiation
-Legalization in Costa Rica
-Business Operating Procedures
-Marketing and Customer Service
-Financing Options
-Projections, Business Products and Services
	-38 participants graduated from the 2 week business trainings
	-68% of participants were women
	-The ages of participants raged from 15 ½-57 years of age.
	-23 of the participants had a developing idea and 15 were already running existing businesses 
 looking to improve them.

2. 10 months of 2 hour/2x weekly English classes taught by a TEFL certified instructor and held at the Nosara Spanish Institute. The English classes are specifically tailored to their individual businesses

3. Logo creation-1 on 1 session with Graphic Designer Zacc Pollitt of Prove Nothing

4. Photo sessions in their business setting with Professional Photographer Veronica Monge for marketing and advertising purposes.

5. 1 on 1 Social Media Sessions with Rebecca Schmidt to learn about and create social media accounts for their businesses. The focus was on learning the basics of social media, creating their accounts, reaching out to their community, attracting new clients and making a social media marketing plan.

**Comment by Viveelsueno** [comment]
![nosara-spanish-institiue-vive-el-sueno 1](https://user-images.githubusercontent.com/35813084/38636944-3141a1e4-3d76-11e8-9fd7-f5046fff1dc5.jpg)
![prove-nothing-playa-guiones-nosara](https://user-images.githubusercontent.com/35813084/38636948-363e3dd8-3d76-11e8-8733-f77cf63b4bb0.jpg)
![community-partners-vivel-el-sueno-ye](https://user-images.githubusercontent.com/35813084/38636963-420de988-3d76-11e8-9b47-a4fc52b82f7f.jpg)
![veronica-monge-photography-costa-rica-vive-el-sueno-nosara1](https://user-images.githubusercontent.com/35813084/38636979-50dc888e-3d76-11e8-970f-83e4aacc819e.jpg)

**Comment by Viveelsueno** [comment]
Please add to bottom of Program Info:

We have exciting news!  We hare able to hold a second 40 hour/2 week Intensive Business Training this year and this will be held in May 2018 in the evenings!!

**Comment by Viveelsueno** [comment]
Below are photos for the 2017-2018 Program

**Comment by edisch** [comment]
Do you have any photos I could use for the team member detail pages? I'm looking for a masthead image so something landscape for each person. Ideally they would be similar in theme but no worries if they are a bit different, just need something to fill the space.

**Comment by edisch** [comment]
For reference: https://modest-liskov-6d2578.netlify.com/team/zacc-pollitt/
![screen shot 2018-04-26 at 4 31 36 pm](https://user-images.githubusercontent.com/1893118/39337016-5c0569f6-496f-11e8-8fb5-6735c37bda2e.png)

**Comment by edisch** [comment]
Yeah, something like a landscape photo if you've got one for each person on the team. Otherwise we can just use some kind of default photo.

**Comment by Viveelsueno** [comment]
Yeah landscape I guess as I don't have pics for everyone only the bios.
This section can be very simple like it was on the last page.  Can you put
Christina in the spot where you currently are please and move you near Zacc
and Veronica?  Thanks
