### ISSUE TITLE
Add 2 new articles to the site

### ISSUE THREAD

**Issue by edisch** [edisch/viveelsueno#2]
Add these 2 articles to our site...where should we put them? Home page?
http://www.nosarastories.com/life-stories/entrepreneur-nosara/
https://www.humansofnosara.org/human/rebecca-schmidt/
http://www.vozdeguanacaste.com/en/articles/2016/06/08/foundation-fulfills-dreams-nosarans-and-helps-them-start-their-own-businesses

**Comment by Viveelsueno** [comment]
Here is an article that was just published by Nosara Stories about one of our participants..please add it as well. 

http://www.nosarastories.com/life-stories/kids-proud-of-me/

**Comment by edisch** [comment]
I've added all these articles to the about page under the "See what others are saying about us" heading: https://modest-liskov-6d2578.netlify.com/about/#see-what-others-are-saying-about-vive-el-sue%C3%B1o

**Comment by edisch** [comment]
Please close this ticket when you are happy with it. Let me know if you have any questions.
