### ISSUE TITLE
Create new participant stories

### ISSUE THREAD

**Issue by edisch** [edisch/viveelsueno#27]
## Steps to Test
- Go to [/participant](https://modest-liskov-6d2578.netlify.com/participant)
- Confirm that each participant's info is correct
- Confirm that the correct photo is associate with each participant
- Change language and run through the previous steps again

**Comment by Viveelsueno** [comment]
2017-2018 Participants Listed Below with Contact info and logo

**Comment by Viveelsueno** [comment]
The people who have opened businesses are first..ones who didn't but whom still graduated form our program are below with much less info

**Comment by Viveelsueno** [comment]
Alicia Artavia 
El Flaco Auto Repuestos 
Mechanic
Arenales, Nosara
2682 0930
https://www.facebook.com/Repuestos-el-flaco-295523117554388/?fref=mentions
![96](https://user-images.githubusercontent.com/35813084/38835777-92cb137c-4178-11e8-8ca8-43f908d3ecb9.jpg)

**Comment by Viveelsueno** [comment]
Iris Jiron Castillo
Cleaning Experts in Home
8539-1974
https://www.facebook.com/Cleaning-Experts-In-Home-1584020191678202/
![104](https://user-images.githubusercontent.com/35813084/38835980-2150adf0-4179-11e8-8832-4cd245d31f5f.jpg)
![Uploading Cleaning-Home-Experts.jpg…]()

**Comment by Viveelsueno** [comment]
Pilar Montiel Noguera
Soda Mapis
Nosara Centro
89681736 2682 0064
https://www.facebook.com/SodaMapis/
![128](https://user-images.githubusercontent.com/35813084/38836539-fa6e6752-417a-11e8-9706-5138413c7295.jpg)
![soda-mapis 1](https://user-images.githubusercontent.com/35813084/38836575-1f7f727a-417b-11e8-8b26-86ac0fbf7aa5.jpg)

**Comment by Viveelsueno** [comment]
Ruth Juarez Cordoba
Cabinas Dilan
Central Nosara next to and also across from the Catholic Church
2682-0371 8610 3738
![cabinas-dilan 1](https://user-images.githubusercontent.com/35813084/38837307-e038980a-417d-11e8-9b48-416f78eec7e1.jpg)
![20](https://user-images.githubusercontent.com/35813084/38837321-eeb870a8-417d-11e8-8657-1749e8314ef9.jpg)

**Comment by Viveelsueno** [comment]
Sara Baltodano Lopez
4 Life Productos Naturales
San Carlos, Nosara
71512656 
![49](https://user-images.githubusercontent.com/35813084/38837475-92e8653e-417e-11e8-9507-46cbe2f8df26.jpg)
![4life-numero2](https://user-images.githubusercontent.com/35813084/38837527-be7227da-417e-11e8-9e0a-ab866cb9feb2.jpg)

**Comment by Viveelsueno** [comment]
Maria Zuñiga Diaz
Tijeras Magicas Peluquería
Magic Scissors Salon
100m West of ICE, Arenales, Nosara
8870 6414
https://www.facebook.com/Magic-Scissors-Salon-540379582703104/?fref=mentions

![05](https://user-images.githubusercontent.com/35813084/38844935-feab1e2e-41a1-11e8-821a-8d2ccb50968b.jpg)
![tijeras-magicas](https://user-images.githubusercontent.com/35813084/38844967-243e6b8c-41a2-11e8-9272-1f4fe1efba9c.jpg)

**Comment by Viveelsueno** [comment]
Diego Lopez Matarrita
Remodelaciones Chorotega
Nosara, Guanacaste
86624660 2201 6493
remodelacioneschorotega@gmail.com 
https://www.facebook.com/DIEGOLOPEZ2077/
![chorotega](https://user-images.githubusercontent.com/35813084/38845405-cf5199bc-41a3-11e8-8bcd-643d0a4a77b1.jpg)
![113](https://user-images.githubusercontent.com/35813084/38845451-ef6e050a-41a3-11e8-8b69-bd81ccdd85a1.jpg)

**Comment by Viveelsueno** [comment]
Arianna Rivera Avilés 
Ari's Boutique
Central Nosara
8674-3627
![28](https://user-images.githubusercontent.com/35813084/38845557-6f0cf686-41a4-11e8-9122-de429eacec2b.jpg)
![ariana](https://user-images.githubusercontent.com/35813084/38845574-885880b0-41a4-11e8-91c4-8a883410a965.jpg)

**Comment by Viveelsueno** [comment]
Heiner Díaz Matarrita
Heyner's Multifuntional Man
83570903 63550374 
https://www.facebook.com/Heyners-Multifuntional-Man-345454742530998/?fref=mentions
![heyner s-multifunctional-man 1](https://user-images.githubusercontent.com/35813084/38845644-f04bcbb4-41a4-11e8-856a-2b0c9d8642da.jpg)
![70](https://user-images.githubusercontent.com/35813084/38845665-06992682-41a5-11e8-8dee-caeb9e4a083b.jpg)

**Comment by Viveelsueno** [comment]
Luis Diego Pérez Jirón
Green Spirit Nosara
 8550 5438
https://www.facebook.com/luisdiego1025/

![168](https://user-images.githubusercontent.com/35813084/38845949-5a325876-41a6-11e8-940d-8439d139a780.jpg)
![green-spirit 1](https://user-images.githubusercontent.com/35813084/38845986-81e6de3c-41a6-11e8-9b1c-4ac4ac249f87.jpg)

**Comment by Viveelsueno** [comment]
Guillermo Mora Arias
Servicios Electro Mecanicos 
Arenales, Nosara
8496 6399, 8484 7904 
https://www.facebook.com/electriconosara/?fref=mentions
![26855501_10160112340735647_1278076334_n](https://user-images.githubusercontent.com/35813084/38846192-96aeba3c-41a7-11e8-9d4f-bf739088f5bb.jpg)
![175](https://user-images.githubusercontent.com/35813084/38846203-a88c819e-41a7-11e8-9297-9c6f71a6065b.jpg)

**Comment by Viveelsueno** [comment]
Sonia Córdoba Porras
Soda Vanessa
Central Nosara 
2682-0371 8610 3738
![16](https://user-images.githubusercontent.com/35813084/38846361-796ecaa6-41a8-11e8-9ef6-7900872ac53b.jpg)
![soda-vanessa](https://user-images.githubusercontent.com/35813084/38846418-b1e5ef18-41a8-11e8-92b5-19ac2a723980.jpg)

**Comment by Viveelsueno** [comment]
Eraida Diaz
Costuras y Pinturas Diaz
8667-4044
![08](https://user-images.githubusercontent.com/35813084/38887855-72ffda42-4226-11e8-95b9-a02bc3e52bdc.jpg)

**Comment by Viveelsueno** [comment]
Heidi Cordero Castillo
Sabor de la Montaña
Finca Integral Don Juan
Zaragoza
8550 7622
![sabor-de-la-montana](https://user-images.githubusercontent.com/35813084/38888183-541bb5dc-4227-11e8-92fe-e1c68a9940ab.jpg)

I don't have any high res photos of her at this time. We plan to do her photo shoot in the near future..I hope.

Here is a photo form her fb
![23472297_1206628002771049_7730156506335294868_n](https://user-images.githubusercontent.com/35813084/38888531-60748c04-4228-11e8-8f5c-e8df6766b0fd.jpg)

**Comment by Viveelsueno** [comment]
Erika Rojas Cambronero
Joer
Beet Salads
Ostional, Guanacaste
8599 3193

![17361759_1845966758991439_6246994868072999571_n 1](https://user-images.githubusercontent.com/35813084/38889514-6972d524-422b-11e8-8150-3d2fd9a53628.jpg)

**Comment by Viveelsueno** [comment]
Joer Logo for above participant Erika
![joer 1](https://user-images.githubusercontent.com/35813084/38889553-8b51f2d8-422b-11e8-93eb-d43bac7719d9.jpg)

**Comment by Viveelsueno** [comment]
Magda Dailey
Almohadas Cari Blue
Pillows and Slip Covers
Nosara
88495270
![almohadas](https://user-images.githubusercontent.com/35813084/38889660-d86fd878-422b-11e8-9b1a-6f2b076abc17.jpg)
![45](https://user-images.githubusercontent.com/35813084/38889672-e285d6fa-422b-11e8-9297-53d2ab4464d8.jpg)

**Comment by Viveelsueno** [comment]
Elena Gomez
La Cuchara de Elena
San Carlos of Nosara
8463 7299
![la-cuchara](https://user-images.githubusercontent.com/35813084/38890048-c672db88-422c-11e8-9374-e83d967a631e.jpg)
![142](https://user-images.githubusercontent.com/35813084/38890096-dfd8a346-422c-11e8-8726-8b96c91797ef.jpg)

**Comment by edisch** [comment]
@Viveelsueno You can start adding these guys straight to the CMS, it will save us both time since you're listing out the names and everything here anyways. If you would like me to handle the image compression and the detail pages I can do that but adding the basic info will speed things up for sure.

To get in, go to forestry.io and log in using your GitHub account. You can add participants in under the participants tab on the left. I'll add a screenshot here in a second showing exactly where.

**Comment by Viveelsueno** [comment]
How do I do this?  I want to link their fb pages to their photos..as in if
you click their photo then it opens to their fb page..if they have
one..only some do. Is this possible?

**Comment by Viveelsueno** [comment]
Ok send me the info cause this is super time consuming for me as well

On Tue, Apr 17, 2018 at 10:55 AM, Vive el Sueno <viveelsuenonosara@gmail.com

**Comment by Viveelsueno** [comment]
Maria Fernanda Alvarado Arrieta
Nosara Beauty Spa
Nosara
8688 1577

https://www.facebook.com/Guanacaste-Beauty-Spa-612004075857866/?fref=mentions
![beauty-spa](https://user-images.githubusercontent.com/35813084/38890243-4e9db7bc-422d-11e8-8e35-e40c880ad10d.jpg)
![136](https://user-images.githubusercontent.com/35813084/38890386-a7ca4f62-422d-11e8-8507-76ac70d50944.jpg)

**Comment by edisch** [comment]
For the images from now on, just leave the participant's name and their photos and I will make sure they are the right size and compressed appropriately.

**Comment by edisch** [comment]
We can make their teaser photo link to their FB page for sure. Leave a link to their FB page as well when you're adding the photos and I'll make sure it's added in there once I create a field for it. Right now they just link directly to the participant's detail page.

**Comment by Viveelsueno** [comment]
Graduates..no photos just names for time and space

Marita Rios
Angelina Noguera
Adriana Salas
Rocio Navarrete
Esmeralda Lopez
Paul Zuñiga 
Karen Vindas
Maritza Juarez
Cristian Castillo
Cherry Acosta
Rolando Lopez
Melissa Arrieta
Jhon Mena 
Yanory Lopez
Juan Ocontrillo

**Comment by edisch** [comment]
If you're having trouble I can run through it quickly with you via Skype.

**Comment by Viveelsueno** [comment]
oops forgot 1 participant with a business..here is the last one

Giovanni Acedo
Tarzan-Comidas de la Jungla
Food Express
8551 1093
![tarzan-food-service](https://user-images.githubusercontent.com/35813084/38890776-da8a1a8a-422e-11e8-97c9-3373a7e25148.jpg)
![tarzan](https://user-images.githubusercontent.com/35813084/38890880-247f3fd0-422f-11e8-8318-d3a88dd34129.jpg)

**Comment by Viveelsueno** [comment]
K I sent all of them

On Tue, Apr 17, 2018 at 10:55 AM, Vive el Sueno <viveelsuenonosara@gmail.com
> wrote:

> Ok send me the info cause this is super time consuming for me as well
>
> On Tue, Apr 17, 2018 at 10:55 AM, Vive el Sueno <

**Comment by Viveelsueno** [comment]
All the participants names, photos, logos and contact info (depending on
what they have) have been added to github. Let me know if you need anything
else

On Tue, Apr 17, 2018 at 11:05 AM, Vive el Sueno <viveelsuenonosara@gmail.com
> wrote:

> K I sent all of them
>
> On Tue, Apr 17, 2018 at 10:55 AM, Vive el Sueno <

**Comment by Viveelsueno** [comment]
We have photo shoots this week for the new success stories so will not have
that info for another week or 2.

On Tue, Apr 17, 2018 at 11:07 AM, Vive el Sueno <viveelsuenonosara@gmail.com
> wrote:

> All the participants names, photos, logos and contact info (depending on
> what they have) have been added to github. Let me know if you need anything
> else
>
> On Tue, Apr 17, 2018 at 11:05 AM, Vive el Sueno <

**Comment by edisch** [comment]
No worries. I'll add these into forestry. Are all the Facebook links here?

I'll set up the site so that you can link to where ever you'd like from the participant teaser. It will link by default to the detail page, if the "Create detail page" checkbox is ticked. It won't link to anything if the checkbox is not ticked and no custom link is set.

How does that sound?

**Comment by Viveelsueno** [comment]
Sounds good.

Only a few of the participants have fb pages and I added the links for all
that do..mostly the top ones.

Thank you

**Comment by edisch** [comment]
@Viveelsueno In the interest of space do you think it would be ok if we used only a single first and last name for the participants? I understand Costa Rican's have a tradition of keeping both family names. Is there usually a more dominant one, would that be the last one?

**Comment by Viveelsueno** [comment]
I think we need to use their full names as there are so many with almost
the same names here.

**Comment by edisch** [comment]
I have added all the new participants. Please run through the steps to test included at the top of the ticket and let me know if any information is wrong.

**Comment by edisch** [comment]
@Viveelsueno ^
