### ISSUE TITLE
Add client side interstitial to collect emails

### ISSUE THREAD

**Issue by edisch** [edisch/viveelsueno#3]
Please add a pop up so we can collect email addresses. I want to start a newsletter asap for here and on mailchimp. (Any advice ont his is welcomed).

## Steps to Test
- Go to the [homepage](https://modest-liskov-6d2578.netlify.com/)
- Scroll down to the socials widget
- Enroll with any email to the newsletter
- Confirm that after hitting subscribe a message appears thanking you for your subscription
- Confirm that the email you enrolled with shows up on the MailChimp list

**Comment by edisch** [comment]
@Viveelsueno Can you get me the login details for mailchimp? I can't log in with the email.

![screen shot 2018-04-27 at 7 46 03 pm](https://user-images.githubusercontent.com/1893118/39391136-af2fc272-4a53-11e8-909b-373d48d3db92.png)

**Comment by edisch** [comment]
I have an endpoint setup for this I just need the login details now and we can close this issue.

**Comment by Viveelsueno** [comment]
#IggyMango1

**Comment by edisch** [comment]
I need the username. You gave me the email and the password. I can't log in without it.

**Comment by Viveelsueno** [comment]
viveelsueno@gmail.com

**Comment by edisch** [comment]
Is there any other information you received from them about MailChimp? If not I need you to go into MailChimp and run through the steps for Forgot my username.

**Comment by Viveelsueno** [comment]
I just tried signing in with no problems

username: viveelsuenonosara@gmail.com
password: #IggyMango1

**Comment by edisch** [comment]
Please run through the steps to test at the top of this ticket. You can close the ticket if everything checks out.

**Comment by edisch** [comment]
@Viveelsueno Please run through the steps to test at the top of this ticket. You can close the ticket if everything checks out.

**Comment by Viveelsueno** [comment]
All good!
