### ISSUE TITLE
Reorder sections

### ISSUE THREAD

**Issue by edisch** [edisch/viveelsueno#37]
Also I want the Program info first and then participants and then the success stories on the homepage.

**Comment by Viveelsueno** [comment]
Can we take the topics part out and add it to the larger program explanation?  Does that make sense?

**Comment by edisch** [comment]
@Viveelsueno That will definitely give us some room to work with. Do you think you could shorten the title a little so it fits on one line too?

**Comment by Viveelsueno** [comment]
Intensive Business Training is fine

**Comment by Viveelsueno** [comment]
How do I look at the site as if I was an outsider again? I cannot find the link or info for some reason

**Comment by edisch** [comment]
https://modest-liskov-6d2578.netlify.com/

**Comment by edisch** [comment]
@Viveelsueno Please take a look at this one and close it if you are happy with the copy on the homepage and the about page (check Spanish too).

**Comment by Viveelsueno** [comment]
Yes the layout looks good
