### ISSUE TITLE
Update participants content

### ISSUE THREAD

**Issue by edisch** [edisch/viveelsueno#38]
- Copy links over from old site and add them to teasers for participants
- Import 2016 participants

**Comment by Viveelsueno** [comment]
how do I look at this again?  I am on forestry.io but how do I see the site as if I was a new

**Comment by edisch** [comment]
@Viveelsueno https://modest-liskov-6d2578.netlify.com/

**Comment by Viveelsueno** [comment]
For the participants- their photos, logos, phone numbers and links to fb pages (if they have them is great).

I would like them to appear in the following order:
2018-how you have them ending with Alicia is great. We are missing many that graduated bu tdidn;t open businesses such as
Marita Rios
Angelina Noguera
Adriana Salas
Rocio Navarrete
Esmeralda Lopez
Paul Zuñiga
Karen Vindas
Maritza Juarez
Cristian Castillo
Cherry Acosta
Rolando Lopez
Melissa Arrieta
Jhon Mena
Yanory Lopez
Juan Ocontrillo
Can we just list their names please?  I do have photos and logos for each but none have opened businesses at this time?  
2017-can you flip the order that you have on the new site.. what I mean by this is can you start with Graciela (who is currently last) and end with Milagro who is below Alicia?
Can you please add 2016 participants?
https://viveelsuenocr.org/local-businesses/program-participants/

**Comment by edisch** [comment]
@Viveelsueno Can you please upload Iris's logo again here? It didn't upload properly on the other ticket.
