### ISSUE TITLE
Add graduation year to participants listing

### ISSUE THREAD

**Issue by edisch** [edisch/viveelsueno#40]
- Add graduation year field to participant content type
- Add graduation years list to site data file
- List graduation years and then participants who graduated in that year

**Comment by Viveelsueno** [comment]
Do you need me to do this?  All the info is on the old site and any I added this year are the 2018 participants

**Comment by edisch** [comment]
I'll handle this content migration.

**Comment by edisch** [comment]
@Viveelsueno I might need you to add the years to the participants once I've added the field. I'll copy them over to the Spanish content just add the year to each of the English participant content pieces. Does that make sense?

**Comment by edisch** [comment]
I need you to go through and fill out the graduation year for each of the participants. Note: there are English and Spanish versions of each participant. I'll update Ivan's business name. If you notice any other participants with the wrong business name it might be faster for you to just go into forestry and update them yourself.

![screen shot 2018-05-11 at 2 32 52 pm](https://user-images.githubusercontent.com/1893118/39943390-4b76dae2-5528-11e8-9690-7e28a784e5a8.png)
